"""Offline eval entry point: ``python -m evalharness.run``.

Builds a synthetic dataset, ranks every deck with three rankers, prints a
metrics table, writes it to docs/ALGORITHM.md, and enforces the gate:

  random floor  <  heuristic  <  oracle ceiling   (on NDCG@5)

The heuristic beating random proves the scorer and plumbing work; staying
below the oracle proves the simulator hides signal as designed (D-007). If
the heuristic does NOT beat random by the margin, the run fails — that is the
regression guard, not a flaky test.
"""

from __future__ import annotations

import argparse
import random
import sys
from collections.abc import Callable
from pathlib import Path

from app.scoring import HeuristicRanker

from .metrics import hit_rate_at_k, mrr, ndcg_at_k, precision_at_k, recall_at_k
from .simulator import EvalInstance, build_instance, generate_users, generate_world

# Default dataset size. Large enough that averaged metrics are stable run to
# run; small enough to finish in well under a second.
DEFAULT_SEED = 20260611
DEFAULT_USERS = 400
DEFAULT_VENUES = 300
CANDIDATES_PER_DECK = 40
KS = (1, 3, 5)

# The heuristic must clear random by at least this NDCG@5 margin or the gate
# fails (the synthetic plumbing is broken).
GATE_MARGIN = 0.05

Ranker = Callable[[EvalInstance], list[str]]

_EVAL_START = "<!-- EVAL:START -->"
_EVAL_END = "<!-- EVAL:END -->"


def _random_ranker(seed: int) -> Ranker:
    rng = random.Random(seed)

    def rank(instance: EvalInstance) -> list[str]:
        ids = [c.id for c in instance.candidates]
        rng.shuffle(ids)
        return ids

    return rank


def _heuristic_ranker() -> Ranker:
    ranker = HeuristicRanker()

    def rank(instance: EvalInstance) -> list[str]:
        ordered = ranker.rank(instance.profile, instance.context, instance.candidates)
        return [r.id for r in ordered]

    return rank


def _oracle_ranker() -> Ranker:
    # Sees the latent utility directly — the achievable ceiling, not shippable.
    def rank(instance: EvalInstance) -> list[str]:
        return sorted(instance.relevance, key=lambda i: instance.relevance[i], reverse=True)

    return rank


def evaluate(ranker: Ranker, instances: list[EvalInstance]) -> dict[str, float]:
    """Average every metric for one ranker across all decks."""
    totals: dict[str, float] = {}
    for instance in instances:
        ranked = ranker(instance)
        for k in KS:
            totals[f"ndcg@{k}"] = totals.get(f"ndcg@{k}", 0.0) + ndcg_at_k(
                ranked, instance.relevance, k
            )
            totals[f"p@{k}"] = totals.get(f"p@{k}", 0.0) + precision_at_k(
                ranked, instance.relevant_ids, k
            )
            totals[f"recall@{k}"] = totals.get(f"recall@{k}", 0.0) + recall_at_k(
                ranked, instance.relevant_ids, k
            )
            totals[f"hit@{k}"] = totals.get(f"hit@{k}", 0.0) + hit_rate_at_k(
                ranked, instance.relevant_ids, k
            )
        totals["mrr"] = totals.get("mrr", 0.0) + mrr(ranked, instance.relevant_ids)
    n = len(instances)
    return {metric: value / n for metric, value in totals.items()}


def _format_table(results: dict[str, dict[str, float]]) -> str:
    header = "| Ranker | NDCG@1 | NDCG@3 | NDCG@5 | P@5 | Recall@5 | Hit@5 | MRR |"
    sep = "|---|---|---|---|---|---|---|---|"
    rows = [header, sep]
    for name in ("random", "heuristic", "oracle"):
        m = results[name]
        rows.append(
            f"| {name} | {m['ndcg@1']:.3f} | {m['ndcg@3']:.3f} | {m['ndcg@5']:.3f} "
            f"| {m['p@5']:.3f} | {m['recall@5']:.3f} | {m['hit@5']:.3f} | {m['mrr']:.3f} |"
        )
    return "\n".join(rows)


def _write_algorithm_doc(table: str, seed: int, n_users: int, n_venues: int) -> None:
    """Replace the generated block in docs/ALGORITHM.md, if the doc is found."""
    doc = Path(__file__).resolve().parents[3] / "docs" / "ALGORITHM.md"
    if not doc.exists():
        return
    block = (
        f"{_EVAL_START}\n"
        f"_Generated by `python -m evalharness.run` "
        f"(seed {seed}, {n_users} users, {n_venues} venues, synthetic). "
        f"Plumbing validation only — not real-world lift (D-007)._\n\n"
        f"{table}\n"
        f"{_EVAL_END}"
    )
    text = doc.read_text(encoding="utf-8")
    if _EVAL_START in text and _EVAL_END in text:
        before = text.split(_EVAL_START)[0]
        after = text.split(_EVAL_END)[1]
        doc.write_text(before + block + after, encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--users", type=int, default=DEFAULT_USERS)
    parser.add_argument("--venues", type=int, default=DEFAULT_VENUES)
    args = parser.parse_args(argv)

    rng = random.Random(args.seed)
    world = generate_world(rng, args.venues)
    users = generate_users(rng, args.users)
    instances = [build_instance(rng, user, world, CANDIDATES_PER_DECK) for user in users]

    results = {
        "random": evaluate(_random_ranker(args.seed), instances),
        "heuristic": evaluate(_heuristic_ranker(), instances),
        "oracle": evaluate(_oracle_ranker(), instances),
    }

    table = _format_table(results)
    print(table)
    _write_algorithm_doc(table, args.seed, args.users, args.venues)

    floor = results["random"]["ndcg@5"]
    heuristic = results["heuristic"]["ndcg@5"]
    ceiling = results["oracle"]["ndcg@5"]
    print(
        f"\nNDCG@5 — floor(random)={floor:.3f}  heuristic={heuristic:.3f}  "
        f"ceiling(oracle)={ceiling:.3f}"
    )

    if heuristic < floor + GATE_MARGIN:
        print(
            f"GATE FAILED: heuristic NDCG@5 {heuristic:.3f} did not beat random "
            f"{floor:.3f} by {GATE_MARGIN}",
            file=sys.stderr,
        )
        return 1
    if heuristic >= ceiling:
        # The oracle uses hidden signal, so the heuristic reaching it means the
        # simulator failed to hide anything — the harness would be circular.
        print(
            f"GATE FAILED: heuristic NDCG@5 {heuristic:.3f} >= oracle {ceiling:.3f}; "
            "simulator is not hiding signal (D-007 violated)",
            file=sys.stderr,
        )
        return 1
    print("GATE PASSED: random < heuristic < oracle")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
